name: Test

on:
  push:
    branches:
      - master

jobs:
  my-test:
    name: Release new version
    runs-on: ubuntu-18.04
    if: github.event_name == 'push' && startsWith(github.event.head_commit.message, '[release]')
    steps:
      - uses: actions/setup-java@v1
        with:
          java-version: 8
          architecture: x64
      - name: Publish new version
        run: |
          git clone ${{ github.repositoryUrl }} .
          git config user.name "${{ github.event.head_commit.committer.name }}"
          git config user.email "${{ github.event.head_commit.committer.email }}"
          export GPG_TTY=$(tty)

