name: Test

on:
  push:
    branches:
      - master

jobs:
  my-test:
    name: My test
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{ github.repositoryUrl }} 
      - run: echo ${{ github.event.head_commit.committer.name }}
      - run: echo ${{ github.event.head_commit.committer.email }}
      - run: echo ${{ github.event.head_commit.message }}
      - run: echo "Is executed"
        if: startsWith(github.event.head_commit.message, '[release]')
