name: Test

on:
  push:
    branches:
      - master

jobs:
  my-test:
    name: My test
    runs-on: ubuntu-18.04
    steps:
      - run: echo ${{ github.repositoryUrl }} 
      - env:
          EMAIL: ${{ github.head_commit.author.email }}
        run: echo $EMAIL
      - run: echo ${{ toJson(github.head_commit) }}
